export const Selectors = {
  currentUserMenuBtn: (user: string) => `button:has-text("${user}")`,
  myAccountHeading: '[role="heading"][name="My account"]',
  emailInput: '[placeholder="Your email"]',
  passwordInput: '[placeholder="Your password"]',
  loginButton: '[role="button"][name="Login"]',
  navMenu: '[data-test="nav-menu"]',
  unmaskPasswordBtn: 'button:has(svg[data-icon="eye"])',
  maskPasswordBtn: 'button:has(svg[data-icon="eye-slash"])',
  forgotPasswordBtn: '[role="link"][name="Forgot your Password?"]',
  registerBtn: '[role="link"][name="Register your account"]',
  emailError: '[data-test="email-error"]',
  passwordError: '[data-test="password-error"]',
  forgotPasswordError: 'text="The selected email is invalid"',
  setNewPasswordBtn: '[role="button"][name="Set New Password"]',
  forgotPasswordEmailInput: '[placeholder="Your email *"]',
};
