name: Create envfile

on: [push]

jobs:

  create-envfile:
 
    runs-on: ubuntu-18.04
 
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_BASE_URL: "https://practicesoftwaretesting.com"
        envkey_ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
        envkey_ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        file_name: .env
